### ISSUE TITLE
Error when switching guilds

### ISSUE THREAD

**Issue by Naught0** [topisani/Discurses#28]
Hi! Love the project so far. It's the best from the current discord-cli clients I've used, however I can't seem to switch guilds / servers reliably.  

Here's a picture of the error since I can't seem to copy-paste it. ![The error](https://u.teknik.io/3PPXl.png)

```
 $ python3 --version
Python 3.6.3
```

Let me know if you'd like any other information!

**Comment by Ge0** [comment]
Hi @Naught0 and thanks a lot for your feedback.

I think that the bug has been fixed in #24 but the update has not been released on pip yet. I have to check with @topisani to do this asap.

In between you can create a virtualenv, clone the repo and `python setup.py install` the good old way.

Cheers,

Ge0

**Comment by Naught0** [comment]
Hey thanks for the prompt response! Sorry I didn't see it. It looks like the git version does indeed work!

**Comment by Ge0** [comment]
No worries :) I'll try to release soon!
